# Generated by Django 5.2.15 on 2026-06-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text="Exact match e.g., 'Software Engineering'", max_length=255)),
                ('country_id', models.CharField(help_text="e.g., 'us', 'in', 'es'", max_length=10)),
                ('language', models.CharField(default='English', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('future_outlook', models.TextField()),
                ('opportunity', models.TextField()),
                ('pro_tip', models.TextField()),
                ('pros', models.JSONField(default=list, help_text='List of strings')),
                ('cons', models.JSONField(default=list, help_text='List of strings')),
                ('how_to', models.JSONField(default=list, help_text='List of strings')),
                ('links', models.JSONField(default=list, help_text="List of objects: [{'name': '...', 'url': '...'}]")),
            ],
            options={
                'unique_together': {('course_id', 'country_id')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('timeframe', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert'), ('Visionary', 'Visionary')], max_length=50)),
                ('description', models.TextField()),
                ('tools', models.JSONField(default=list, help_text='List of strings')),
                ('milestones', models.JSONField(default=list, help_text='List of strings')),
                ('anti_patterns', models.JSONField(blank=True, default=list, help_text='List of strings', null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
