# Generated by Django 5.2.15 on 2026-06-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Check this if this is a Premium roadmap'),
        ),
    ]
