# Generated by Django 5.2.15 on 2026-06-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together={('course_id', 'country_id', 'language')},
        ),
    ]
