# Generated by Django 5.2.15 on 2026-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_alter_roadmap_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='cons',
            field=models.TextField(blank=True, default='', help_text='Type each con on a new line'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='how_to',
            field=models.TextField(blank=True, default='', help_text='Type each step on a new line'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='pros',
            field=models.TextField(blank=True, default='', help_text='Type each pro on a new line (e.g. - High pay)'),
        ),
        migrations.AlterField(
            model_name='roadmapstep',
            name='anti_patterns',
            field=models.TextField(blank=True, default='', help_text='Type each anti-pattern on a new line'),
        ),
        migrations.AlterField(
            model_name='roadmapstep',
            name='milestones',
            field=models.TextField(blank=True, default='', help_text='Type each milestone on a new line'),
        ),
        migrations.AlterField(
            model_name='roadmapstep',
            name='tools',
            field=models.TextField(blank=True, default='', help_text='Type each tool on a new line'),
        ),
    ]
